adapt/README.md
adapt/haskell-nix.nix
default.nix
flake.nix
lib/default.nix
lib/src.nix
nix/sources.json
tests/default.nix
tests/test-bar/file
tests/test-foo/file

I’m trying to reuse IOHK’s `cleanGit`. The idea is that I want to be able to first clean the top-level dir, then, if needed, restrict all of it to a subdir.
The problem is that, apparently, haskell.nix’s git doesn’t work without a `subDir` argument :/.
The test case for this branch is:
```
nix-build -E '(import <nixpkgs> {}).stdenv.mkDerivation { name = "test"; src = (import ./.).lib.src.cleanGit "test" ./.; }'
```
it gives me:
```
error: the string '/nix/store/ipg5hw6pzqpx3sy4zxqjxfa7912lb9mw-test/.reuse/dep5' is not allowed to refer to a store path (such as '/nix/store/ipg5hw6pzqpx3sy4zxqjxfa7912lb9mw-test'), at /nix/store/cl038kzg67j1d6f83zxqlzbmi00kjwif-source/lib/clean-git.nix:34:23
```
I suspect that somewhere inside the `cleanGit` filter they collect strings returned by `git` and …

WIP: Make clean-git from haskell.nix more modular

---

modules/vault-secrets.nix

Allow to set a system-wide prefix used to resolve the EnvironmentFile path used
for authentication.
This allows us to prefix AppRole names for pseudo-namespacing, along with the
environment file provisioning script, without also having to prefix every secret
name as well.

[OPS-1085] vault-secrets: Add approlePrefix option

---

modules/common.nix

Wasabi died again, and our CI died with it. Prevent this in the future by allowing Nix to build locally in case substitution fails.

Enable nix fallback in case wasabi dies

---

flake.nix

`nix flake` commands from nix-unstable don't work currently because the
haskell.nix pin is old and it's incompatible with the pinned
nix-unstable. The haskell.nix input in this flake is not used anywhere,
so it should be ok to just remove it to fix this problem

[OPS-1144] Remove haskell.nix input to fix the flake

---

modules/acme-sh.nix

acme.sh allows setting a group for the certificate directory, but the
mode needs to be changed to let the group actually access it.
This change does not make existing setups less secure, because the group
is 'root' by default.

[OPS-1003] acme.sh: let configured group access the certificate

---

lib/default.nix
lib/types.nix

We are using the idiom of "untyped config, all definitions should merge, output json" quite often, so I figured it would make sense to make a type for it. There are 5 new types added to `lib.types`, descriptions for them are in the code.

Add types with recursively merged attrs

---

modules/virtualization/hetzner-cloud.nix

Hetzner cloud instances have dhcp for ipv4, but not for ipv6, so ipv6
has to be configured statically.

[OPS-1146] Add option to set IPv6 address for hetzner cloud instances

---

overlay/default.nix

Problem: `checkTrailingWhitespace` checks all files for trailing
whitespaces except for binary files. However, there are more files
we want to exclude:
1. We want to exclude `.patch` files because patched code may have
trailing whitespaces, sometimes it's out of our control.
2. We want to exclude licenses because they may contain trailing
whitespaces and normally licenses should be copy-pasted as is.
Our licenses normally don't contain trailing whitespaces, and even
if some license does, we can remove them. But removing them from
licenses that apply to code we copy-pasted is not perfect, we'd
rather not do that.
Solution: update `checkTrailingWhitespace` to exclude `LICENSES`
directory and `*.patch` files.
1. I see that we use mere `grep` that can also scan files outside of the repo. For …

[INT-147] Update 'checkTrailingWhitespace'

---

modules/ssh-hostkeys.nix

Sadalbari was redeployed to fix https request flooding issues, so the key needs to be updated.

[OPS-1163] Update host key for sadalbari

---

scripts/update-youtrack.sh

Prior to this, running the script would fail with
```
fatal: 'upd-youtrack-https://download.jetbrains.com/charisma/youtrack-2020.6.3319.jar' is not a valid branch name.
```
or later
```
scripts/update-youtrack.sh: line 28: CUR: unbound variable
```
This fixes both of these issues, there is also a cosmetic issue with `$NOTES_LINK` not being a valid URL which has not been addressed here

Fix youtrack update script

---

flake.lock
modules/acme-sh.nix

`utillinuxMinimal` was renamed to `util-linuxMinimal` in https://github.com/NixOS/nixpkgs/commit/bc49a0815ae860010b4d593b02f00ab6f07d50ea

[OPS-821] Bump nixpkgs, update util-linux package name in acme-sh module

---

flake.nix
modules/virtualization/ec2.nix

I've noticed that acme and vault-secrets services may fail during boot, complaining about dns server not set up. It happens when an ipv6 address is assigned before an ipv4 address, so making dhcp always wait for an ipv4 address before starting other services will fix it. I've made a config for it with other common ec2 setup, so we can reuse it across all repos.

[OPS-1176] Create a module for common ec2 setup, add a fix for network services failing on boot

---

lib/default.nix
lib/systemd/default.nix
lib/systemd/harden-services.nix
lib/systemd/profiles.nix

Adds lib/systemd.nix, which contains hardening profiles for systemd
units. isolate is the best one, but it will break most useful units
from working; backend is for a typical backend application, it allows
some restricted networking, and backend_unix_sockets allows only UNIX
socket networking.

Add systemd hardening profiles

---

modules/serokell-users.nix

This does not break API. All existing code should continue to work as before. This feature is opt-in.
Particular use cases I have in mind:
* Adding all wheel users to `docker`, so they don't have to `sudo` every time.
* Setting up group-based `sudo` rules and adding all regular users to that group.
* Specific services that allow granting certain privileges based on groups without needing `sudo`.

Allow adding extra groups to users and wheel users

---

flake.nix
modules/wireguard-monitoring.nix

Moves the module which exports prometheus node exporter metrics over wireguard from aquarius, so we can use it for other infras too

[OPS-1138] Move monitoring module from aquarius-infra

---

modules/acme-sh.nix

Make sure acme.sh does not start before consul during booting or
configuration switch.

[OPS-1197] acme.sh: add dependency on consul when consul lock is used

---

modules/acme-sh.nix

https://github.com/serokell/serokell.nix/pull/38 didn't invoke `optional` correctly

[OPS-1197] Fix typo in acme-sh dependency on consul

---

flake.lock
overlay/youtrack.nix

`stdenv.lib` was deprecated in https://github.com/NixOS/nixpkgs/commit/6717246373541f92ac8d044c6ad1224700686a47 and will be removed in the next NixOS release

[OPS-1202] Bump nixpkgs, change `stdenv.lib` to `lib`

---

modules/common.nix

Having dhcpcd for docker interfaces causes it to create `169.254.0.0/16` route for link-local routing (because it does not get a DHCP offer), and it breaks access to the default AWS NTP server, and breaks time synchronization for EC2 instances. This issue is described in https://github.com/NixOS/nixpkgs/issues/109389.
Disabling dhcpcd for interfaces matching `veth*` fixes it. It's unclear if there can be other interfaces named `veth*`, which are not created by docker and actually require DHCP, but we definitely don't have that in our infrastructure.

[OPS-1230] Disable dhcpcd for docker network interfaces to fix EC2 NTP

---

lib/default.nix

It was added to nixpkgs as `composeManyExtensions` https://github.com/NixOS/nixpkgs/commit/c3b35f21f78a3d23aaf40b70fe8865598ddc6729
It seems like we didn't import it anywhere, so it's trivial to remove it

Remove `foldExtensions`

---

modules/common.nix
modules/services/nginx.nix

I've made `openFirewall` from our own `nginx` module only affect the configuration when nginx is enabled, enabled `recommendedGzipSettings` (this is pretty standard though we do not use this anywhere else, is there any reason?), and copied the `commonHttpConfig` from https://nixos.wiki/wiki/Nginx - we should heavily scrutinize these options as they have the ability to cause many issues, the only important part we really want is the HSTS header.

Harden nginx options

---

modules/common.nix

Adding HSTS headers is broken if there is an `add_headers` directive in
some virtualHost config. Make it optional.

Make HSTS headers optional

---

modules/acme-sh.nix

acme.sh [switched][1] to using ZeroSSL by default, and now require an email
address. This broke our module. Which I think is good, since it actually
gives us a good chance to switch back to trusted LE instead of rather sketchy
ZeroSSL.
[1]: https://github.com/acmesh-official/acme.sh/commit/d0b514890a28d13e83bb06efcfb14651e83360c5

Fix acme.sh (by switching back to letsencrypt)

---

lib/haskell.nix

Provide a standard set of build options for CI builds of haskell.nix packages: `-Werror`, Haddock, etc.
(This PR depends on #51 (it does not really depend on it functionally, but it is that other PR that starts the Haskell lib).)

ciBuildOptions for haskell.nix packages

---

lib/haskell.nix

It turns out, passing `ghc` to *Project functions is deprecated.
The correct thing to do is pass the string name of the compiler as
`compiler-nix-name`. This has something to do with cross-sompilation and
choosing the right compiler in the right pkg set.
Pass `compiler-nix-name` to *Project instead of `ghc`.
This also magically fixed builds with GHC 9.2.1 (they removed the
`Option` newtype in `base`, which broke some packages, including
`hashable`, but the version of `hashable` that fixes this depends on
`ghc-bignum`, which only exists in GHC >=9). I don’t exactly know why,
but it does. Probably something to do with the internals of haskell.nix.

fix: Correctly request GHC in makeFlake

---

modules/common.nix
modules/wireguard-monitoring.nix

This should handle all processes by default, the /nix/store regex comes from an example in nixpkgs, then I added an additional wildcard match afterwards to handle all the other processes.

Run prometheus process exporter

---

modules/common.nix

This should help us tackle issues like those we are having with Agora. I would much rather something dies than a server freezes.

Enable earlyoom by default

---

modules/common.nix

so we can see things like `dotnet Tzkt.Sync.dll` and `dotnet Tzkt.Api.dll`, not just `dotnet`

More granular process matching

---

modules/ssh-keys.nix

Problem: ixahedron's SSH key isn't in ssh-keys.nix.
Solution: added ixahedron's public key to the ssh-keys.nix list.

[Chore] Add ixahedron's SSH key

---

flake.lock
flake.nix
lib/default.nix
lib/pipeline.nix

this is a migration of `mkPipeline` and `mkPipelineFile` from https://github.com/serokell/common-infra/blob/master/flake.nix - though I have also updated it to use newer nix commands (`nix build` not `nix-build`), default `ciSystem` to the first item under `systems` (same as for the `writeText` under `mkPipelineFile`), and fixed https://github.com/serokell/common-infra/issues/4.

Add mkPipeline

---

modules/common.nix

They were cool, I like them, but they absolutely kill prometheus and all of our nodes. Wherever needed we can add granularity for matching specific programs.

Ignore arguments in process exporter

---

overlay/default.nix

Looks like we made it not work with the terraform directory being simply `/terraform`, whoops :/

Fix terraform path in terraformWithModules

---

modules/common.nix
modules/serokell-users.nix

Problem: During CI a lot of trace warnings will be emitted
Solution: Rename the affected options to resolve and thereby silence the warnings

Update option names to silence CI

---

.buildkite/pipeline.yml

Problem: The CI uses `nix-shell` to check this flake. This is not necessary anymore with the updated nix version on the CI server
Solution: Update CI command to `nix flake check -L`

Update CI command

---

modules/common.nix

Problem: 'common' module uses 'nixWrapper' to override default 'nix.package'. However, 'nixWrapper' may be not available when this module is imported.
Solution: Explicitly import overlay from nixwrapper in 'common' module.

Use nixwrapper overlay in common module

---

overlay/default.nix

Problem: Sometimes trailing whitespaces are found within '.git' directory which isn't the problem of the sources this script is run on.
Solution: Exclude this directory from scanning for trailing whitespaces.

Exclude '.git' directory from check-trailing-whitespace

---

modules/ssh-hostkeys.nix

Problem: LIGO CI needs an ability to do deployments to the tejat-prior server.
Solution: Add its key to the list of known hosts.

Add tejat-prior to the list of known hosts

---

flake.nix
overlay/default.nix

Problem: Consistently profiling the speed of two versions of software is usually not very reliable due to the processes being interrupted by background tasks, thereby rendering execution speed comparisons nearly useless on busy systems.
Solution: A wrapper that moves all background tasks off of a number of cpus and runs the benchmarks on the newly freed cpus.

Add a cgroup wrapper for benchmarking

---

overlay/default.nix

Problem: The benchwrapper did not inherit the working directory from the calling shell. This leads to a lot of undefined behaviour
Solution: add the `-d` flag to sytemd-run to inherit the pwd from the calling shell

Fix the benchwrapper's pwd

---

modules/common.nix

Problem: the atop service logs in a certain directory and upon restarting the service a script checks wether it needs to update the lockfiles to a new update. that does not work as intended and leads to a *lot* of duplicate files in the log directory
Solution: since atop is not being used currently, it is being disabled

Disable atop service

---

overlay/default.nix

Problem: Standard 'diff' output is not very descriptive in case changes reorder lines in the file.
Solution: Use 'diff -u' instead to give 'git diff'-like diff output.

Enhance stylish-haskell check

---

modules/serokell-users-options.nix
modules/ssh-keys.nix

Problem: Philipp is leaving our company, so we need to revoke all accesses that he has.
Solution: Remove his ssh key from the list and also remove his user from the wheel.

Remove Philipp's ssh key from the config

---

modules/ssh-hostkeys.nix

Problem: we need to deploy from GA to algenib, but we get a `Host verification failed` issue
Solution: we have to add algenib's ssh pub key to the list of known hosts which will be later imported in the aquarius-infra  and deployed to our github runners

[INT-237] Add algenib to the list of known hosts

---

modules/ssh-hostkeys.nix

Problem: We need to add staging.ment.serokell.team to known hosts for the CD to work.
Solution: Add pubKey for staging.ment.serokell.team.

[Chore] Add staging.ment.serokell.team to known hosts

---

overlay/default.nix

Problem: We want to be able to check in our CIs if the cabal files are up to date.
Solution: Add hpack check.

[Chore] Add hpack check

---

lib/terraform.nix

Problem: When using terraform, we often need vault access.
Solution: Add vault login to terraform app script to avoid manual login.

[Chore] Add vault login to terraform app

---

modules/ssh-hostkeys.nix

Problem: we have a machine for the new-website staging and we'd like to reach it from Github Action via deploy-rs
Solution: add the vm's pub ssh host key to our list of host keys

[OPS-1460] Add anadolu to ssh-hostkeys

---

modules/ssh-hostkeys.nix

Problem: we have a new vm for haskell certification from the master branch, called alkabar. We want to deploy to it from Github Actions, but can't as its ssh host key is unknown
Solution: Add it's ssh host key to the known host keys list.

[INT-243] Add alkabar to ssh known hosts

---

modules/ssh-hostkeys.nix

Problem: we would like to support in CI the prod env for haskell certification
Solution: Add the VM's ssh host key to our list of known hosts

[INT-243] Support biham in ssh known hosts

---

modules/wireguard-monitoring-darwin.nix
modules/wireguard-monitoring.nix

Problem: We want some VPN clients to be able to access other clients. However, currently the only allowed IP address is the VPN server.
Solution: Add an option to provide arbitrary allowed IPs for the wireguard client config.

Make wireguard allowed IPs configurable

---

flake.nix
modules/wireguard-monitoring/common.nix
modules/wireguard-monitoring/darwin.nix
modules/wireguard-monitoring/default.nix

Problem: Some VPN clients might be behind NAT or firewall and thus they
may not be able to receive incoming messages after some period of time.
Solution: Make it possible to set some 'PersistentKeepalive' value to
workaround this limitation.

Make 'PersistentKeepalive' configurable for VPN clients 

---

modules/ssh-hostkeys.nix

Problem: we decommissioned alkabar from pegasus, we want to cleanup the leftovers
Solution: delete alkabar's host ssh key

Remove alkabar

---

overlay/default.nix

Problem: In order to publish a package to hackage, it must meet certain requirements, which can be verified using cabal check.
Solution: Add cabal check.
Related to https://github.com/serokell/nix-templates/pull/24

[OPS-1477] Add cabal check

---

modules/common-non-darwin.nix

Problem: We have added an alert rule for systemd services stuck in a restart loop, this requires systemd restart metrics to be enabled.
Solution: Add --collector.systemd.enable-restarts-metrics to node exporter config.

[Chore] Enable restarts metrics for systemd services

---

modules/wireguard-monitoring/default.nix

Problem: we would like to see the logs also for user-level systemd services, until now we saw only accumulated from all services from a user which was inconvenient (user@10xx.service)
Solution: Extend promtail to add also the user_id  and in the case of user-level services use the value of the `_systemd_user_unit` instead of  `_systemd_unit` which is usually `init.scope`

Add to Promtail user_id, override unit if we have a _systemd_user_unit

---

modules/common-non-darwin.nix

Problem: Some options used in serokell.nix were deprecated and renamed.
Solution: Use updated options names.

[Repin] Update used options

---

modules/wireguard-monitoring/default.nix

Problem: we would like to be alerted when something goes wrong in Nginx logs. For this we need to collect these logs.
Solution: we need a conditional promtail scrape config to gather Nginx error logs, based on the presence of Nginx

Support nginx error logs in promtail scrape configs

---

lib/default.nix
lib/haskell.nix

Problem: Our CI template for libraries allows one to specify ghc-versions so that we can build a library in different configurations. Currently the only configurable thing is the GHC version. We also want to be able to build libraries with different stack.yaml files and stack resolvers.
Solution: Add a haskell.nix wrapper to the library CI capable of building a project with different GHC versions, stack.yaml files, and stack resolvers.

[OPS-1458] Add haskell.nix wrapper for CI

---

flake.nix
modules/postgresql-migration.nix

Problem: From time to time we need to update the version of postgresql running on our infra. When a major version of postgres is changed, usually, a dedicated migration for data directory is needed.
Solution: To remove the necessity to do the migration manually, introduce a module that will add a oneshot service which will perform a migration prior to starting postresql service.

Add module with oneshot service for postgresql migration

---

modules/ssh-hostkeys.nix

Problem: We need to add skat.aquarius.serokell.team to known hosts for the CD to work.
Solution: Add pubKey for skat.aquarius.serokell.team.

[ITMO-7] Add skat host-key

---

modules/ssh-hostkeys.nix

Problem: we would like to decommission anadolu, and we'd like to remove its leftovers from this repo too
Solution: remove the vm's pub ssh host key from our list of host keys
related issues: https://issues.serokell.io/issue/SIO-405

Revemo anadolu's ssh key

---

flake.lock
overlay/default.nix
overlay/github.nix

Problem: Some of our projects have a job in the CI pipeline that creates GitHub release with some release artifacts. We'd like to unify the approach for creating such releases.
Solution: Add autorelease script to 'lib.github.autorelease'.

Add helper script for creating GitHub releases using gh

---

lib/systemd/default.nix
lib/systemd/user-level-services.nix

Problem: We have many projects where we deploy similar approaches with user-level systemd services. We need to reduce duplication.
Solution: create a flexible enough lib to cover all the best practices
Related issue(s)
https://issues.serokell.io/issue/OPS-1467
https://github.com/serokell/haskell-certification/pull/456
https://github.com/serokell/new-serokell-website/pull/69
https://github.com/serokell/pont/pull/958

[OPS-1467] Introduce mkActivateScript for user-level systemd services

---

lib/systemd/user-level-services.nix

Problem: in one of the consumers of user-level-servics.nix we bumped into a problem where a hand-crafted pkgs was used. As we didn't pass to the nixpkgs.lib.nixosSystem the incoming pkgs, the consumer didn't work as expected.
Solution: pass pkgs to nixpkgs.lib.nixosSystem too

[OPS-1467] Fix missing pkgs in user-level-services.nix

---

flake.lock

Problem: we bumped into a problem with the latest serokell/nixpkgs and we needed to repin again. We want to use here also the lattest nixpkgs.
Solution: nix flake lock --update-input nixpkgs

[OPS-1514] Repin nixpkgs

---

.github/workflows/check.yml
flake.lock
flake.nix
modules/virtualization/docker.nix
tests/docker.nix

Problem: Our nixpkgs fork has a commit that makes it possible to define named docker networks declaratively. However, it seems like it doesn't work as expected. We want to fix it and move to serokell.nix repo instead.
Solution. Fix problems, add the ability to recreate networks, add warnings, extract everything as a separate module.

[OPS-1463] Docker networks and volumes

---

modules/ssh-keys.nix

Problem: Oliver no longer works with us.
Solution: Remove his ssh key from 'ssh-keys.nix'.

[Chore] Remove Oliver's ssh key

---

lib/default.nix
lib/systemd/default.nix
lib/systemd/profiles.nix

Problem: We want to harden our systemd services by using previously defined profiles, so we need a way to easily apply them to our systemd service configurations.
Solution: Add withHardeningProfile helper, remove DeviceAllow from profiles, because it is used incorrectly (systemd complains and skips this option), and the semantics of this use is already covered by PrivateDevices.

[OPS-1161] Add `withHardeningProfile` helper

---

modules/wireguard-monitoring/default.nix

Problem: Some of our services run as containers orchestrated not by systemd. Currently, logs for such containers aren't easily searchable in promtail.
Solution: Add '__journal_container_name' to the promtail relabeling in case docker is enabled within the configuration

[Chore] Relabel '__journal_container_name' when docker is enabled

---

modules/ssh-keys.nix

Problem: For FAP-26, I need to SSH into a server, but I need permission first.
Solution: Add my key to ssh-keys.nix.

[FAP-26] Add Heitor's SSH key

---

flake.lock
flake.nix
overlay/default.nix

Problem: We want to be able to check our Haskell applications for dead code. This can be done using weeder.
Solution: Add weeder check to our overlay.

[Chore] Add weeder check

---

modules/common-non-darwin.nix
modules/common.nix

Problem: For historical reasons, this overlay existed and was using serokell-nix's 'inputs', which in some cases causes issues (see #101). However, nowadays, the overlay only provides utilities used by the CI/CD pipelines and thus there is no sense in using it system-wide.
Solution: Remove 'nixpkgs.overlay' from 'common' module, remove 'inputs' from argument attrset for 'common' module as well.

[Chore] Remove 'nixpkgs.overlay' from 'common' module

---

overlay/github.nix

Problem: 'gh release create' pushes the tag only when it doesn't exist, i.e. it won't attempt to update already existing tag with a given name. As a result, subsequent update of a given release (e.g. auto-release) won't update the underlying tag.
Solution: If 'OVERWRITE_RELEASE' flag is provided, both existing release and tag are deleted.

[Chore] Overwrite tag with release in 'github.autorelease'
